### ISSUE TITLE
error building 32bit linux

### ISSUE THREAD

**Issue by smolleyes** [iteufel/nwjs-ffmpeg-prebuilt#28]
hello

already had this error ? 

python build_ffmpeg.py -c -nw 0.19.2 -ta ia32 -pc

everything fine then

```
-o obj/third_party/ffmpeg/ffmpeg_internal/hevc_cabac.o -x c ../../third_party/ffmpeg/libavcodec/hevc_cabac.c 
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module '../../third_party/ffmpeg/libavcodec/hevc_cabac.c'.
4.	Running pass 'Greedy Register Allocator' on function '@ff_hevc_part_mode_decode'
clang: error: unable to execute command: Aborted (core dumped)
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 4.0.0 (trunk 282487)
Target: i386-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/nwjs_build/build_dir/ffmpeg/nwjs-ffmpeg-prebuilt/build/src/out/nw/../../third_party/llvm-build/Release+Asserts/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/hevc_cabac-2b36ca.c
clang: note: diagnostic msg: /tmp/hevc_cabac-2b36ca.sh
clang: note: diagnostic msg: 

********************
[408/448] CC obj/third_party/ffmpeg/ffmpeg_internal/h264qpel.o
ninja: build stopped: subcommand failed.
ERROR: Traceback (most recent call last):
  File "build_ffmpeg.py", line 98, in main
    build(target_cpu)
  File "build_ffmpeg.py", line 409, in build
    subprocess.check_call('ninja -C out/nw ffmpeg', shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'ninja -C out/nw ffmpeg' returned non-zero exit status 1

```

thanks

**Comment by vzamanillo** [comment]
Same for me :/

**Comment by smolleyes** [comment]
damn :(

something changed in ffmpeg, was working before since you builded it :p

i search for changes in upstream

**Comment by smolleyes** [comment]
it works if i use --disable-asm but don t know if it has side-effects :/

**Comment by smolleyes** [comment]
main ffmpeg delevloper say:

<JEEB> that looks like a bug in clang 4 rather than FFmpeg, no?
 I mean, clang crashed
 also llvm+clang 4.0 isn't even stable yet
 see: http://llvm.org/
 so yes, go provide a bug report to the llvm+clang people
 it shouldn't crash

....

**Comment by vzamanillo** [comment]
You are tenacious, thank you very much!

**Comment by smolleyes** [comment]
yes... i do it once for all and next time in 3 years lol

**Comment by vzamanillo** [comment]
Confirmed, the build ends with success disabling asm, thank you very much!!

**Comment by vzamanillo** [comment]
Same asm related errors on building for windows x64

`../../third_party/ffmpeg/libavcodec/x86/vp8dsp_loopfilter.asm:1584: error: invalid size for operand 1`
