### ISSUE TITLE
error building on windows

### ISSUE THREAD

**Issue by smolleyes** [iteufel/nwjs-ffmpeg-prebuilt#31]
hi m8

the adventure continue, now on windows

i installed all the needed tools, build njws os ok , now ffmpeg under cygwin i have a strange error and it won  t build 

configure / make ok then ... (installed yasm git diffutils and make thru cygwin installer)

```
License: LGPL version 2.1 or later
Creating config.mak, config.h, and doc/config.texi...
Running ['make', '-j8', 'libavcodec/avcodec-57.dll', 'libavformat/avformat-57.dll', 'libavutil/avutil-55.dll']
CC      libavformat/allformats.o
CC      libavformat/avio.o
CC      libavformat/aviobuf.o
CC      libavformat/cutils.o
CC      libavformat/dump.o
cl▒: Ligne de commande warning D9002▒: option '/home/sylvain/nwjs-ffmpeg-prebuilt/build/src/third_party/ffmpeg/libavformat/allformats.c' inconnue ignor▒e
cl▒: Ligne de commande error D8003▒: nom de fichier de la source absent
CC      libavformat/file_open.o
make: *** [/home/sylvain/nwjs-ffmpeg-prebuilt/build/src/third_party/ffmpeg/common.mak:60: libavformat/allformats.o] Error 2
make: *** Attente des tâches non terminées....
CC      libavformat/flac_picture.o
cl▒: Ligne de commande warning D9002▒: option '/home/sylvain/nwjs-ffmpeg-prebuilt/build/src/third_party/ffmpeg/libavformat/avio.c' inconnue ignor▒e
cl▒: Ligne de commande error D8003▒: nom de fichier de la source absent
make: *** [/home/sylvain/nwjs-ffmpeg-prebuilt/build/src/third_party/ffmpeg/common.mak:60: libavformat/avio.o] Error 2
CC      libavformat/format.o
cl▒: Ligne de commande warning D9002▒: option '/home/sylvain/nwjs-ffmpeg-prebuilt/build/src/third_party/ffmpeg/libavformat/aviobuf.c' inconnue ignor▒e
cl▒: Ligne de commande error D8003▒: nom de fichier de la source absent
make: *** [/home/sylvain/nwjs-ffmpeg-prebuilt/build/src/third_party/ffmpeg/common.mak:60: libavformat/aviobuf.o] Error 2
cl▒: Ligne de commande warning D9002▒: option '/home/sylvain/nwjs-ffmpeg-prebuilt/build/src/third_party/ffmpeg/libavformat/cutils.c' inconnue ignor▒e
cl▒: Ligne de commande error D8003▒: nom de fichier de la source absent
make: *** [/home/sylvain/nwjs-ffmpeg-prebuilt/build/src/third_party/ffmpeg/common.mak:60: libavformat/cutils.o] Error 2
cl▒: Ligne de commande warning D9002▒: option '/home/sylvain/nwjs-ffmpeg-prebuilt/build/src/third_party/ffmpeg/libavformat/dump.c' inconnue ignor▒e
cl▒: Ligne de commande error D8003▒: nom de fichier de la source absent
make: *** [/home/sylvain/nwjs-ffmpeg-prebuilt/build/src/third_party/ffmpeg/common.mak:60: libavformat/dump.o] Error 2
cl▒: Ligne de commande warning D9002▒: option '/home/sylvain/nwjs-ffmpeg-prebuilt/build/src/third_party/ffmpeg/libavformat/file_open.c' inconnue ignor▒e
cl▒: Ligne de commande error D8003▒: nom de fichier de la source absent
make: *** [/home/sylvain/nwjs-ffmpeg-prebuilt/build/src/third_party/ffmpeg/common.mak:60: libavformat/file_open.o] Error 2
cl▒: Ligne de commande warning D9002▒: option '/home/sylvain/nwjs-ffmpeg-prebuilt/build/src/third_party/ffmpeg/libavformat/flac_picture.c' inconnue ignor▒e
cl▒: Ligne de commande error D8003▒: nom de fichier de la source absent
make: *** [/home/sylvain/nwjs-ffmpeg-prebuilt/build/src/third_party/ffmpeg/common.mak:60: libavformat/flac_picture.o] Error 2
cl▒: Ligne de commande warning D9002▒: option '/home/sylvain/nwjs-ffmpeg-prebuilt/build/src/third_party/ffmpeg/libavformat/format.c' inconnue ignor▒e
cl▒: Ligne de commande error D8003▒: nom de fichier de la source absent
make: *** [/home/sylvain/nwjs-ffmpeg-prebuilt/build/src/third_party/ffmpeg/common.mak:60: libavformat/format.o] Error 2
Traceback (most recent call last):
  File "./chromium/scripts/build_ffmpeg.py", line 648, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./chromium/scripts/build_ffmpeg.py", line 613, in main
    configure_args)
  File "./chromium/scripts/build_ffmpeg.py", line 605, in do_build_ffmpeg
    options.config_only, branding, configure_flags)
  File "./chromium/scripts/build_ffmpeg.py", line 220, in BuildFFmpeg
    ['make', '-j%d' % parallel_jobs] + libraries, cwd=config_dir)
  File "./chromium/scripts/build_ffmpeg.py", line 95, in PrintAndCheckCall
    subprocess.check_call(argv, *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j8', 'libavcodec/avcodec-57.dll', 'libavformat/avformat-57.dll', 'libavutil/avutil-55.dll']' returned non-zero exit status 2
ERROR: Traceback (most recent call last):
  File "build_ffmpeg.py", line 96, in main
    check_build_with_proprietary_codecs(proprietary_codecs, host_platform, target_arch)
  File "build_ffmpeg.py", line 464, in check_build_with_proprietary_codecs
    subprocess.check_call('./chromium/scripts/build_ffmpeg.py {0} {1}'.format(host_platform, target_arch), shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)

```

to translate...
cl▒: Ligne de commande warning D9002▒: option '/home/sylvain/nwjs-ffmpeg-prebuilt/build/src/third_party/ffmpeg/libavformat/allformats.c' inconnue ignor▒e

= 

cl : command line warning D9002 : blablabla allformats.c' ignored

then D8003 source filename is missing .. Oo ?

nwjs build was all right with exact same config :(

an idear ?? :(

thanks !!

**Comment by smolleyes** [comment]
ok fixed !

2 things

i had to be in /cygrive/c and not in /home, first error

second error, i had many cygwin_wrapper not available... i had to tweak the ninja command to use -j1 and not j8 and i have my zip build :) 

maybe add an option to choose the number of threads for the build ? 

thanks !

**Comment by vzamanillo** [comment]
Hey! 

Very good idea.
