### ISSUE TITLE
Error "FAILED: genversion genversion.map.gz " 

### ISSUE THREAD

**Issue by Ajeey** [iteufel/nwjs-ffmpeg-prebuilt#37]
I have cloned your repo and trying to build it via

`python build_ffmpeg.py  --target x64 --proprietary_codecs`

And I am getting the following error -

```
Writing: ./ffmpeg_generated.gni
INFO: Generating ninja files...
ERROR at //.gn:44:22: Build argument has no effect.
  v8_enable_gdbjit = false
                     ^----
The variable "v8_enable_gdbjit" was set as a build argument
but never appeared in a declare_args() block in any buildfile.

To view all possible args, run "gn args --list <builddir>"
Done. Made 42 targets from 47 files in 68ms
INFO: Starting ninja for building ffmpeg...
ninja: Entering directory `out/nw'
[150/541] LINK ./genversion
FAILED: genversion genversion.map.gz 
python "../../build/toolchain/gcc_link_wrapper.py" --output="./genversion" --map-file "./genversion.map.gz" -- ../../third_party/llvm-build/Release+Asserts/bin/clang++ -Wl,--fatal-warnings -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -Wl,--no-as-needed -lpthread -Wl,--as-needed -fuse-ld=gold -B../../third_party/binutils/Linux_x64/Release/bin -Wl,--threads -Wl,--thread-count=4 -Wl,--icf=all -flto -fwhole-program-vtables -Wl,-plugin-opt,O1 -Wl,-plugin-opt,-function-sections -m64 -pthread -Wl,-O1 -Wl,--gc-sections --sysroot=../../build/linux/debian_jessie_amd64-sysroot -L/home/denimuser/Desktop/nwjs-ffmpeg-prebuilt/build/src/build/linux/debian_jessie_amd64-sysroot/lib/x86_64-linux-gnu -Wl,-rpath-link=/home/denimuser/Desktop/nwjs-ffmpeg-prebuilt/build/src/build/linux/debian_jessie_amd64-sysroot/lib/x86_64-linux-gnu -L/home/denimuser/Desktop/nwjs-ffmpeg-prebuilt/build/src/build/linux/debian_jessie_amd64-sysroot/usr/lib/x86_64-linux-gnu -Wl,-rpath-link=/home/denimuser/Desktop/nwjs-ffmpeg-prebuilt/build/src/build/linux/debian_jessie_amd64-sysroot/usr/lib/x86_64-linux-gnu -L/home/denimuser/Desktop/nwjs-ffmpeg-prebuilt/build/src/build/linux/debian_jessie_amd64-sysroot/usr/lib/gcc/x86_64-linux-gnu/4.6 -Wl,-rpath-link=/home/denimuser/Desktop/nwjs-ffmpeg-prebuilt/build/src/build/linux/debian_jessie_amd64-sysroot/usr/lib/gcc/x86_64-linux-gnu/4.6 -L/home/denimuser/Desktop/nwjs-ffmpeg-prebuilt/build/src/build/linux/debian_jessie_amd64-sysroot/usr/lib -Wl,-rpath-link=/home/denimuser/Desktop/nwjs-ffmpeg-prebuilt/build/src/build/linux/debian_jessie_amd64-sysroot/usr/lib -fsanitize=cfi-vcall -Wl,-rpath-link=./lib -Wl,--disable-new-dtags -Werror -o "./genversion" -Wl,--start-group @"./genversion.rsp"  -Wl,--end-group  -ldl -lrt 
/usr/bin/ld.gold: warning: ignoring --threads: /usr/bin/ld.gold was compiled without thread support
/usr/bin/ld.gold: warning: ignoring --thread-count: /usr/bin/ld.gold was compiled without thread support
/usr/bin/ld.gold: error: treating warnings as errors
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[159/541] CC obj/third_party/yasm/re2c/code.o
ninja: build stopped: subcommand failed.
ERROR: Traceback (most recent call last):
  File "build_ffmpeg.py", line 101, in main
    build(target_cpu)
  File "build_ffmpeg.py", line 396, in build
    subprocess.check_call('ninja -C out/nw ffmpeg', shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'ninja -C out/nw ffmpeg' returned non-zero exit status 1

```

My OS version - Ubuntu 14.04 LTS

**Comment by iteufel** [comment]
@Ajeey i'm working on it.

**Comment by iteufel** [comment]
If the issue still exists just write it down and I will reopen the issue.
