### ISSUE TITLE
Build Error with Ubuntu 18.04 and nw.js 0.30.0 / 5

### ISSUE THREAD

**Issue by marc7000** [iteufel/nwjs-ffmpeg-prebuilt#61]
Hi

i have tried to build the libffmpeg.so with nwjs 0.30.0 and 0.30.5 (x64) under ubuntu 18.04 but i am getting some errors.
See output below...

```
localadmin@Ubuntu-VirtualBox:~$ git clone https://github.com/iteufel/nwjs-ffmpeg-prebuilt.git
Cloning into 'nwjs-ffmpeg-prebuilt'...
remote: Counting objects: 314, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 314 (delta 2), reused 6 (delta 2), pack-reused 306
Receiving objects: 100% (314/314), 80.04 KiB | 347.00 KiB/s, done.
Resolving deltas: 100% (166/166), done.
localadmin@Ubuntu-VirtualBox:~$ cd nwjs-ffmpeg-prebuilt/
localadmin@Ubuntu-VirtualBox:~/nwjs-ffmpeg-prebuilt$ sudo python build_ffmpeg.py --target_arch=x64 -nw=0.30.0
[sudo] password for localadmin: 
INFO: Setting nw version to 0.30.0
INFO: Building ffmpeg for 0.30.0 on linux for x64, proprietary_codecs = False
Creating /home/localadmin/nwjs-ffmpeg-prebuilt/build directory...
INFO: Cleaning output directory...
INFO: Cloning Chromium depot tools in /home/localadmin/nwjs-ffmpeg-prebuilt/build...
Cloning into 'depot_tools'...
remote: Counting objects: 998, done
remote: Finding sources: 100% (998/998)
remote: Total 998 (delta 119), reused 559 (delta 119)
Receiving objects: 100% (998/998), 2.52 MiB | 5.06 MiB/s, done.
Resolving deltas: 100% (119/119), done.
INFO: Creating .gclient file...
Running depot tools as root is sad.
INFO: Cloning Chromium source code for nw-0.30.0 in /home/localadmin/nwjs-ffmpeg-prebuilt/build
Cloning into 'src'...
remote: Counting objects: 289009, done.
remote: Compressing objects: 100% (207892/207892), done.
remote: Total 289009 (delta 91684), reused 169686 (delta 73004), pack-reused 0
Receiving objects: 100% (289009/289009), 887.10 MiB | 7.83 MiB/s, done.
Resolving deltas: 100% (91684/91684), done.
Note: checking out '004e06da11e10bb08f6632224ae48ee3d5f7b303'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Checking out files: 100% (292554/292554), done.
INFO: Hard source code reset to nw 0.30.0 specified version
HEAD is now at 004e06da11 nwjs master
INFO: Cleaning previous DEPS and BUILD.gn backup files...
INFO: Backing up and overwriting DEPS...
INFO: Backing up and overwriting BUILD.gn...
INFO: Installing build dependencies...
ERROR: The only supported distros are
 	Ubuntu 14.04 (trusty)
 	Ubuntu 16.04 (xenial)
 	Ubuntu 17.10 (artful)
 	Debian 8 (jessie) or later
INFO: Syncing with gclient...
Running depot tools as root is sad.
/home/localadmin/nwjs-ffmpeg-prebuilt/build/.gclient_entries missing, .gclient file in parent directory /home/localadmin/nwjs-ffmpeg-prebuilt/build might not be the file you want to use.
Syncing projects: 100% (10/10), done.                                    

________ running '/usr/bin/python src/build/linux/sysroot_scripts/install-sysroot.py --arch=x86' in '/home/localadmin/nwjs-ffmpeg-prebuilt/build'
Installing Debian Sid i386 root image: /home/localadmin/nwjs-ffmpeg-prebuilt/build/src/build/linux/debian_sid_i386-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/15b7efb900d75f7316c6e713e80f87b9904791b1/debian_sid_i386_sysroot.tar.xz
Hook '/usr/bin/python src/build/linux/sysroot_scripts/install-sysroot.py --arch=x86' took 12.19 secs
Running hooks:  28% ( 2/ 7) sysroot_x64
________ running '/usr/bin/python src/build/linux/sysroot_scripts/install-sysroot.py --arch=x64' in '/home/localadmin/nwjs-ffmpeg-prebuilt/build'
Installing Debian Sid amd64 root image: /home/localadmin/nwjs-ffmpeg-prebuilt/build/src/build/linux/debian_sid_amd64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/15b7efb900d75f7316c6e713e80f87b9904791b1/debian_sid_amd64_sysroot.tar.xz
Hook '/usr/bin/python src/build/linux/sysroot_scripts/install-sysroot.py --arch=x64' took 10.94 secs
Running hooks:  57% ( 4/ 7) clang        
________ running '/usr/bin/python src/tools/clang/scripts/update.py --if-needed' in '/home/localadmin/nwjs-ffmpeg-prebuilt/build'
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-325667-1.tgz .......... Done.
Running hooks: 100% ( 7/ 7) gn_linux64
________ running 'download_from_google_storage --no_resume --no_auth --bucket chromium-gn -s src/buildtools/linux64/gn.sha1' in '/home/localadmin/nwjs-ffmpeg-prebuilt/build'
0> Downloading src/buildtools/linux64/gn...
Downloading 1 files took 15.339980 second(s)
Hook 'download_from_google_storage --no_resume --no_auth --bucket chromium-gn -s src/buildtools/linux64/gn.sha1' took 15.48 secs
Running hooks: 100% (7/7), done.      
INFO: Generating ninja files...
ERROR at //build/config/linux/pkg_config.gni:103:17: Script returned non-zero exit code.
    pkgresult = exec_script(pkg_config_script, args, "value")
                ^----------
Current dir: /home/localadmin/nwjs-ffmpeg-prebuilt/build/src/out/nw/
Command: python -- /home/localadmin/nwjs-ffmpeg-prebuilt/build/src/build/config/linux/pkg-config.py -s /home/localadmin/nwjs-ffmpeg-prebuilt/build/src/build/linux/debian_sid_amd64-sysroot -a x64 glib-2.0 gmodule-2.0 gobject-2.0 gthread-2.0
Returned 1.
stderr:

Traceback (most recent call last):
  File "/home/localadmin/nwjs-ffmpeg-prebuilt/build/src/build/config/linux/pkg-config.py", line 233, in <module>
    sys.exit(main())
  File "/home/localadmin/nwjs-ffmpeg-prebuilt/build/src/build/config/linux/pkg-config.py", line 139, in main
    prefix = GetPkgConfigPrefixToStrip(options, args)
  File "/home/localadmin/nwjs-ffmpeg-prebuilt/build/src/build/config/linux/pkg-config.py", line 80, in GetPkgConfigPrefixToStrip
    "--variable=prefix"] + args, env=os.environ)
  File "/usr/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

See //build/config/linux/BUILD.gn:83:3: whence it was called.
  pkg_config("glib") {
  ^-------------------
See //build/config/compiler/BUILD.gn:198:18: which caused the file to be included.
    configs += [ "//build/config/linux:compiler" ]
                 ^------------------------------
ERROR: Traceback (most recent call last):
  File "build_ffmpeg.py", line 101, in main
    build(target_cpu)
  File "build_ffmpeg.py", line 423, in build
    subprocess.check_call('gn gen //out/nw "--args=is_debug=false is_component_ffmpeg=true target_cpu=\\\"%s\\\" is_official_build=true ffmpeg_branding=\\\"Chrome\\\""' % target_cpu, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'gn gen //out/nw "--args=is_debug=false is_component_ffmpeg=true target_cpu=\"x64\" is_official_build=true ffmpeg_branding=\"Chrome\""' returned non-zero exit status 1

```

**Comment by iteufel** [comment]
@marc7000 ubuntu 18.04 is currently not supported for building chromium.
14.4 and 16.4 should work fine.

https://chromium.googlesource.com/chromium/src/+/lkcr/docs/linux_build_instructions.md#System-requirements

**Comment by marc7000** [comment]
Thank you! I've tried it with 17.10.1 and it work too.
